name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What version of draw_tree are you using?
      description: Please provide the version number.
      placeholder: e.g., 0.1.0
      value: "0.1.0"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see and provide a screenshot if appropriate.
      value: "A bug happened!"
    validations:
      required: true
