name: Documentation Improvement
description: Suggest a change to the draw_tree documentation.
title: "[Documentation]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation improvement request!
  - type: textarea
    id: request-details
    attributes:
      label: Requested documentation improvement
      description: Please provide details about the documentation improvement you would like to see.
      placeholder: Describe the documentation improvement in detail.
      value: "A documentation improvement suggestion!"
    validations:
      required: true
